name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get  install -y devscripts fakeroot debhelper

      - name: Install YARA
        run: |
          git clone --depth 1 https://github.com/plusvic/yara.git yara3
          cd yara3
          bash ./build.sh
          ./configure
          make
          cp ./yara ../php-malware-finder/
          cd ..

      - name: Run tests
        run: make tests

      - name: Build debian package
        run: make deb
